# Sphinx configuration for the uniqc-cppsimulator documentation.
#
# Build (from the repository root, with a venv that has the extension and
# sphinx installed):
#     .venv-docs/bin/python -m sphinx -b html docs docs/_build/html
#
# Loading this file first runs prepare.py, which copies the repository
# markdown sources (README, CHANGELOG, benchmark docs and plots) into
# docs/includes/ -- the Sphinx source tree may only contain documents under
# its own root, so the copies bridge that boundary.

import os
import sys

sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import prepare  # noqa: E402  (docs/prepare.py, made importable just above)

prepare.prepare()

project = "uniqc-cppsimulator"
copyright = "2026, Agony"
author = "Agony"

try:
    from importlib.metadata import version as _dist_version

    release = _dist_version("uniqc-cppsimulator")
except Exception:  # noqa: BLE001 - docs build fine without an installed dist
    release = "unknown"
version = release

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}

autodoc_member_order = "bysource"
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}
add_module_names = True

language = "zh_CN"

# -- Markdown sources (copied in by prepare.py) ---------------------------
# Heading anchors let in-page links such as readme.md#性能基准 resolve.
myst_heading_anchors = 3

# -- HTML theme ----------------------------------------------------------
# No source_repository/edit button: pages under includes/ are generated by
# prepare.py and git-ignored, so an "edit on GitHub" link would 404 there.
html_theme = "furo"
html_title = "uniqc-cppsimulator"

# The benchmark package is pure Python, but importing it pulls in the
# uniqc_cpp extension; both are available in the documented environment.
suppress_warnings: list[str] = []
