project(UniqcCppCore)
set(UniqcCppCoreSrc_H
    ${CMAKE_CURRENT_SOURCE_DIR}/basic_math.h
    ${CMAKE_CURRENT_SOURCE_DIR}/density_operator_simulator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/errors.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qopcode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/rng.h
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_density_op_impl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_impl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_statevector_impl.h
)
set(UniqcCppCoreSrc
    ${CMAKE_CURRENT_SOURCE_DIR}/basic_math.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/density_operator_simulator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qopcode.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_density_op_impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/simulator_statevector_impl.cpp
)
add_library(${PROJECT_NAME} STATIC ${UniqcCppCoreSrc_H} ${UniqcCppCoreSrc})
